<?php

namespace Proxies\__CG__\JetCharters\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Airport extends \JetCharters\AppBundle\Entity\Airport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'lfiCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'type', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'icaoCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'iataCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'faaCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'name', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'city', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'state', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'countryCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'latitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'longitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'nLatitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'nLongitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'elevation', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'operatingHours', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'utcConversion', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCity', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCityDistanceMiles', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCityDistanceKm', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'centralBusinessDirection', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'maxRunway', 'charterAircraft', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'emptyLegOrigin', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'emptyLegDestination', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'slug');
        }

        return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'lfiCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'type', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'icaoCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'iataCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'faaCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'name', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'city', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'state', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'countryCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'latitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'longitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'nLatitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'nLongitude', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'elevation', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'operatingHours', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'utcConversion', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCity', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCityDistanceMiles', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'closestCityDistanceKm', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'centralBusinessDirection', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'maxRunway', 'charterAircraft', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'emptyLegOrigin', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'emptyLegDestination', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Airport' . "\0" . 'slug');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Airport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLfiCode($lfiCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLfiCode', array($lfiCode));

        return parent::setLfiCode($lfiCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getLfiCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLfiCode', array());

        return parent::getLfiCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcaoCode($icaoCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcaoCode', array($icaoCode));

        return parent::setIcaoCode($icaoCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcaoCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcaoCode', array());

        return parent::getIcaoCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setIataCode($iataCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIataCode', array($iataCode));

        return parent::setIataCode($iataCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIataCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIataCode', array());

        return parent::getIataCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaaCode($faaCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaaCode', array($faaCode));

        return parent::setFaaCode($faaCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaaCode', array());

        return parent::getFaaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryCode($countryCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryCode', array($countryCode));

        return parent::setCountryCode($countryCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryCode', array());

        return parent::getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setElevation($elevation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElevation', array($elevation));

        return parent::setElevation($elevation);
    }

    /**
     * {@inheritDoc}
     */
    public function getElevation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElevation', array());

        return parent::getElevation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperatingHours($operatingHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperatingHours', array($operatingHours));

        return parent::setOperatingHours($operatingHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatingHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatingHours', array());

        return parent::getOperatingHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtcConversion($utcConversion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtcConversion', array($utcConversion));

        return parent::setUtcConversion($utcConversion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtcConversion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtcConversion', array());

        return parent::getUtcConversion();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosestCity($closestCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosestCity', array($closestCity));

        return parent::setClosestCity($closestCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosestCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosestCity', array());

        return parent::getClosestCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosestCityDistanceMiles($closestCityDistanceMiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosestCityDistanceMiles', array($closestCityDistanceMiles));

        return parent::setClosestCityDistanceMiles($closestCityDistanceMiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosestCityDistanceMiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosestCityDistanceMiles', array());

        return parent::getClosestCityDistanceMiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosestCityDistanceKm($closestCityDistanceKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosestCityDistanceKm', array($closestCityDistanceKm));

        return parent::setClosestCityDistanceKm($closestCityDistanceKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosestCityDistanceKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosestCityDistanceKm', array());

        return parent::getClosestCityDistanceKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralBusinessDirection($centralBusinessDirection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralBusinessDirection', array($centralBusinessDirection));

        return parent::setCentralBusinessDirection($centralBusinessDirection);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralBusinessDirection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralBusinessDirection', array());

        return parent::getCentralBusinessDirection();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxRunway($maxRunway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxRunway', array($maxRunway));

        return parent::setMaxRunway($maxRunway);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxRunway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxRunway', array());

        return parent::getMaxRunway();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalAircraft($totalAircraft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalAircraft', array($totalAircraft));

        return parent::setTotalAircraft($totalAircraft);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalAircraft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalAircraft', array());

        return parent::getTotalAircraft();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addCharterAircraft(\JetCharters\AppBundle\Entity\CharterAircraft $charterAircraft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCharterAircraft', array($charterAircraft));

        return parent::addCharterAircraft($charterAircraft);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCharterAircraft(\JetCharters\AppBundle\Entity\CharterAircraft $charterAircraft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCharterAircraft', array($charterAircraft));

        return parent::removeCharterAircraft($charterAircraft);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharterAircraft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharterAircraft', array());

        return parent::getCharterAircraft();
    }

    /**
     * {@inheritDoc}
     */
    public function setNLatitude($nLatitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNLatitude', array($nLatitude));

        return parent::setNLatitude($nLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getNLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNLatitude', array());

        return parent::getNLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setNLongitude($nLongitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNLongitude', array($nLongitude));

        return parent::setNLongitude($nLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getNLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNLongitude', array());

        return parent::getNLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmptyLeg(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmptyLeg', array($emptyLeg));

        return parent::addEmptyLeg($emptyLeg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmptyLeg(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmptyLeg', array($emptyLeg));

        return parent::removeEmptyLeg($emptyLeg);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmptyLeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmptyLeg', array());

        return parent::getEmptyLeg();
    }

    /**
     * {@inheritDoc}
     */
    public function getAirportCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirportCode', array());

        return parent::getAirportCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmptyLegOrigin(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLegOrigin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmptyLegOrigin', array($emptyLegOrigin));

        return parent::addEmptyLegOrigin($emptyLegOrigin);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmptyLegOrigin(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLegOrigin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmptyLegOrigin', array($emptyLegOrigin));

        return parent::removeEmptyLegOrigin($emptyLegOrigin);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmptyLegOrigin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmptyLegOrigin', array());

        return parent::getEmptyLegOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmptyLegDestination(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLegDestination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmptyLegDestination', array($emptyLegDestination));

        return parent::addEmptyLegDestination($emptyLegDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmptyLegDestination(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptyLegDestination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmptyLegDestination', array($emptyLegDestination));

        return parent::removeEmptyLegDestination($emptyLegDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmptyLegDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmptyLegDestination', array());

        return parent::getEmptyLegDestination();
    }

}
