<?php

namespace Proxies\__CG__\JetCharters\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OperatorBillingInformation extends \JetCharters\AppBundle\Entity\OperatorBillingInformation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'aircraftFleet', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'couponCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'billCycle', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'totalCost', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'cardType', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'cardNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'expireDate', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'ccvNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'renewalTerm', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'operator');
        }

        return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'aircraftFleet', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'couponCode', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'billCycle', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'totalCost', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'cardType', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'cardNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'expireDate', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'ccvNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'renewalTerm', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\OperatorBillingInformation' . "\0" . 'operator');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OperatorBillingInformation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAircraftFleet($aircraftFleet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAircraftFleet', array($aircraftFleet));

        return parent::setAircraftFleet($aircraftFleet);
    }

    /**
     * {@inheritDoc}
     */
    public function getAircraftFleet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAircraftFleet', array());

        return parent::getAircraftFleet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouponCode($couponCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouponCode', array($couponCode));

        return parent::setCouponCode($couponCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouponCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouponCode', array());

        return parent::getCouponCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillCycle($billCycle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillCycle', array($billCycle));

        return parent::setBillCycle($billCycle);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillCycle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillCycle', array());

        return parent::getBillCycle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCost($totalCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCost', array($totalCost));

        return parent::setTotalCost($totalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCost', array());

        return parent::getTotalCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardType($cardType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardType', array($cardType));

        return parent::setCardType($cardType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardType', array());

        return parent::getCardType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardNumber($cardNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardNumber', array($cardNumber));

        return parent::setCardNumber($cardNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardNumber', array());

        return parent::getCardNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpireDate($expireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpireDate', array($expireDate));

        return parent::setExpireDate($expireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpireDate', array());

        return parent::getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcvNumber($ccvNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcvNumber', array($ccvNumber));

        return parent::setCcvNumber($ccvNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcvNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcvNumber', array());

        return parent::getCcvNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRenewalTerm($renewalTerm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRenewalTerm', array($renewalTerm));

        return parent::setRenewalTerm($renewalTerm);
    }

    /**
     * {@inheritDoc}
     */
    public function getRenewalTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenewalTerm', array());

        return parent::getRenewalTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\JetCharters\AppBundle\Entity\Operator $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperator(\JetCharters\AppBundle\Entity\Operator $operator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperator', array($operator));

        return parent::setOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperator', array());

        return parent::getOperator();
    }

}
