<?php

namespace Proxies\__CG__\JetCharters\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CharterAircraft extends \JetCharters\AppBundle\Entity\CharterAircraft implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'operator', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'statuslog', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'emptylegs', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'images', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'videos', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'model', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'name', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'seats', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'tailNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'location', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'availableFrom', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'availableTo', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'active', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hourlyRate', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hourlyRate2', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'airAmbulance', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hideTailNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'realTailNumber');
        }

        return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'operator', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'statuslog', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'emptylegs', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'images', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'videos', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'model', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'name', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'seats', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'tailNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'location', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'availableFrom', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'availableTo', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'active', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hourlyRate', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hourlyRate2', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'airAmbulance', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'hideTailNumber', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\CharterAircraft' . "\0" . 'realTailNumber');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CharterAircraft $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeats($seats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeats', array($seats));

        return parent::setSeats($seats);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeats', array());

        return parent::getSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailNumber($tailNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailNumber', array($tailNumber));

        return parent::setTailNumber($tailNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailNumber', array());

        return parent::getTailNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableFrom($availableFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableFrom', array($availableFrom));

        return parent::setAvailableFrom($availableFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableFrom', array());

        return parent::getAvailableFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableTo($availableTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableTo', array($availableTo));

        return parent::setAvailableTo($availableTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableTo', array());

        return parent::getAvailableTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourlyRate($hourlyRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourlyRate', array($hourlyRate));

        return parent::setHourlyRate($hourlyRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourlyRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourlyRate', array());

        return parent::getHourlyRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourlyRate2($hourlyRate2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourlyRate2', array($hourlyRate2));

        return parent::setHourlyRate2($hourlyRate2);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourlyRate2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourlyRate2', array());

        return parent::getHourlyRate2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirAmbulance($airAmbulance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirAmbulance', array($airAmbulance));

        return parent::setAirAmbulance($airAmbulance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirAmbulance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirAmbulance', array());

        return parent::getAirAmbulance();
    }

    /**
     * {@inheritDoc}
     */
    public function setHideTailNumber($hideTailNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHideTailNumber', array($hideTailNumber));

        return parent::setHideTailNumber($hideTailNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getHideTailNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHideTailNumber', array());

        return parent::getHideTailNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealTailNumber($realTailNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealTailNumber', array($realTailNumber));

        return parent::setRealTailNumber($realTailNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealTailNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealTailNumber', array());

        return parent::getRealTailNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperator(\JetCharters\AppBundle\Entity\Operator $operator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperator', array($operator));

        return parent::setOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperator', array());

        return parent::getOperator();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', array());

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmptyleg(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptylegs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmptyleg', array($emptylegs));

        return parent::addEmptyleg($emptylegs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmptyleg(\JetCharters\AppBundle\Entity\CharterAircraftEmptyLeg $emptylegs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmptyleg', array($emptylegs));

        return parent::removeEmptyleg($emptylegs);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmptylegs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmptylegs', array());

        return parent::getEmptylegs();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatuslog(\JetCharters\AppBundle\Entity\AircraftStatusLog $statuslog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatuslog', array($statuslog));

        return parent::addStatuslog($statuslog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatuslog(\JetCharters\AppBundle\Entity\AircraftStatusLog $statuslog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatuslog', array($statuslog));

        return parent::removeStatuslog($statuslog);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatuslog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatuslog', array());

        return parent::getStatuslog();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\JetCharters\AppBundle\Entity\CharterAircraftImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($image));

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\JetCharters\AppBundle\Entity\CharterAircraftImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($image));

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(\JetCharters\AppBundle\Entity\AircraftModel $Model = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($Model));

        return parent::setModel($Model);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function getAircraftModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAircraftModel', array());

        return parent::getAircraftModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAircraftModel(\JetCharters\AppBundle\Entity\AircraftModel $model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAircraftModel', array($model));

        return parent::setAircraftModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoName($videoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoName', array($videoName));

        return parent::setVideoName($videoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoName', array());

        return parent::getVideoName();
    }

    /**
     * {@inheritDoc}
     */
    public function addVideo(\JetCharters\AppBundle\Entity\Video $videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVideo', array($videos));

        return parent::addVideo($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideo(\JetCharters\AppBundle\Entity\Video $videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideo', array($videos));

        return parent::removeVideo($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideos', array());

        return parent::getVideos();
    }

}
