<?php

namespace Proxies\__CG__\JetCharters\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Video extends \JetCharters\AppBundle\Entity\Video implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'aircraftModel', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'charterAircraft', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'videoName', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'updatedAt', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'size');
        }

        return array('__isInitialized__', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'aircraftModel', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'charterAircraft', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'videoName', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'updatedAt', '' . "\0" . 'JetCharters\\AppBundle\\Entity\\Video' . "\0" . 'size');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Video $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setVideoName($videoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoName', array($videoName));

        return parent::setVideoName($videoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoName', array());

        return parent::getVideoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', array($video));

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', array());

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAircraftModel(\JetCharters\AppBundle\Entity\AircraftModel $aircraftModel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAircraftModel', array($aircraftModel));

        return parent::setAircraftModel($aircraftModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAircraftModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAircraftModel', array());

        return parent::getAircraftModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharterAircraft(\JetCharters\AppBundle\Entity\CharterAircraft $charterAircraft = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharterAircraft', array($charterAircraft));

        return parent::setCharterAircraft($charterAircraft);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharterAircraft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharterAircraft', array());

        return parent::getCharterAircraft();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array());

        return parent::getSize();
    }

}
